Election/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    url(r'^home/',include('home.urls')),
    url(r'^registration/',include('registration.urls')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.login, name='log-in'),
    # /index/
    url(r'index/$', views.IndexView.as_view(), name='index'),
    # /home/<candidate_id>/voted
    url(r'index/voted/$', views.voted, name='voted'),
    # /result/
    url(r'result/$', views.result, name='result'),

    # for login
    # url(r'login/$', views.user_login, name='login'),

    # url(r'candidate/(?P<pk>[0-9]+)/detail/$', views.CandidateDetail.as_view(), name='candidate_detail'),
    #
    # # for adding candidate
    #
    # # url(r'^candidate/add/$',views.add_candidate,name = 'add_candidate'),
    #
    # url(r'candidate/add/$',views.CandidateCreate.as_view(),name = 'add_candidate'),
    #
    # url(r'candidate/(?P<pk>[0-9]+)/delete/$', views.CandidateDelete.as_view(), name='candidate_delete'),
    #
    # url(r'candidate/(?P<pk>[0-9]+)/update/$', views.CandidateUpdate.as_view(), name='candidate_update'),
    # for admin dashboard
    # url(r'admin/$',views.home, name='myadmin'),
    # display the list of candidates

]

registration/urls.py
from django.conf.urls import url

from . import views
app_name = 'registration'
urlpatterns = [
    url(r'^$', views.homeView, name='homeView'),
    url(r'register/$',views.register,name = 'register'),
    url(r'create/$',views.simple,name = 'simple'),
    url(r'winners/$',views.winnerList,name = 'winners'),
    # url(r'viewresult/$',views.viewresult,name = 'viewresult'),

    # URLs for creating the models are listed here
    url(r'add-candidate/$',views.CandidateCreate.as_view(),name = 'candidate_add'),
    url(r'add-election/$',views.ElectionCreate.as_view(),name = 'election_add'),
    url(r'add-party/$',views.PartyCreate.as_view(),name = 'party_add'),
    url(r'add-post/$',views.PostCreate.as_view(),name = 'post_add'),
    url(r'add-college/$',views.CollegeCreate.as_view(),name = 'college_add'),
    url(r'add-student/$',views.StudentCreate.as_view(),name = 'student_add'),

    # URLs for updating the models are listed her

    url(r'update-candidate/(?P<pk>[0-9]+)$',views.CandidateUpdate.as_view(),name = 'candidate_update'),
    url(r'update-election/(?P<pk>[0-9]+)$',views.ElectionUpdate.as_view(),name = 'election_update'),
    url(r'update-party/(?P<pk>[0-9]+)$',views.PartyUpdate.as_view(),name = 'party_update'),
    url(r'update-post/(?P<pk>[0-9]+)$',views.PostUpdate.as_view(),name = 'post_update'),
    url(r'update-college/(?P<pk>[0-9]+)$',views.CollegeUpdate.as_view(),name = 'college_update'),
    url(r'update-student/(?P<pk>[0-9]+)$',views.StudentUpdate.as_view(),name = 'student_update'),

    # URLs for reading the models are listed below

    url(r'list-candidate/$',views.CandidateList.as_view(),name = 'candidate_list'),
    url(r'list-election/$',views.ElectionList.as_view(),name = 'election_list'), #This one is errorenous
    url(r'list-party/$',views.PartyList.as_view(),name = 'party_list'),
    url(r'list-post/$',views.PostList.as_view(),name = 'post_list'),
    url(r'list-college/$',views.CollegeList.as_view(),name = 'college_list'),
    url(r'list-student/$',views.StudentList.as_view(),name = 'student_list'),


    # URLs for deleting the models are listed below

    url(r'delete-candidate/(?P<pk>[0-9]+)$',views.CandidateDelete.as_view(),name = 'candidate_delete'),
    url(r'delete-election/(?P<pk>[0-9]+)$',views.ElectionDelete.as_view(),name = 'election_delete'), #This one is errorenous
    url(r'delete-party/(?P<pk>[0-9]+)$',views.PartyDelete.as_view(),name = 'party_delete'),
    url(r'delete-post/(?P<pk>[0-9]+)$',views.PostDelete.as_view(),name = 'post_delete'),
    url(r'delete-college/(?P<pk>[0-9]+)$',views.CollegeDelete.as_view(),name = 'college_delete'),
    url(r'delete-student/(?P<pk>[0-9]+)$',views.StudentDelete.as_view(),name = 'student_delete'),


    # URL to log a user out

    url(r'logout/$',views.logout_view,name = 'logout')
]

home/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

POST =(('PRE','President'),
       ('VPR','Vice-President'),
       ('SEC', 'Secretary'),
       ('MEM','Member'),
       ('TRE','Treasurer'))

PARTY = (('UML','CPN-UML'),('MAOIST','CPN - MAOIST'),('CONGRESS','NEPALI CONGRESS'),('INDEPENDENT','INDEPENDENT'),
         ('MPRF','Madhesi Pepole\'s Right Forum'))

# POST = ['President','Vice-President','Secretary','Treasurer','Member']

# Create your models here.
# class Voter(models.Model):
#     name = models.CharField(max_length=30)
#
# class Candidate(models.Model):
#     name = models.CharField(max_length=30)
#     post = models.CharField(max_length=3, choices=POST)
#     party = models.CharField(max_length=30,choices = PARTY)
#     votes = models.IntegerField(default=0)
#     image = models.FileField(upload_to='static/candidates/',null = True)
#
#     @python_2_unicode_compatible
#     def __str__(self):
#         return self.name

home/forms.py
from django import forms
# from .models import Candidate

from registration.models import Candidate,Student,Party,College,Post,Election

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

# class CandidateForm(forms.ModelForm):
#     class Meta:
#         model = Candidate
#         exclude = ['votes']


class StudentForm(forms.ModelForm):
	class Meta:
		model=Student
		fields=['voter_id','name','sex','dob','disability','college_id','college_name','citizenship_no','photo']


class CandidateForm(forms.ModelForm):
	class Meta:
		model=Candidate
		fields=['voter_id','party_id','post','college_id','candidate_id','election_id']


class PartyForm (forms.ModelForm):
	class Meta:
		model=Party
		fields=['name','registration_no','symbol']


class CollegeForm (forms.ModelForm):
	class Meta:
		model=College
		fields=['name','location','registration_no']


class PostForm (forms.ModelForm):
	class Meta:
		model=Post
		fields=['post_name','post_election']

class ElectionForm (forms.ModelForm):
	class Meta:
		model=Election
		fields=['name','year']

home/views.py
from django.shortcuts import get_object_or_404, render,redirect,render_to_response
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse,reverse_lazy
from django.views import generic
from django.contrib.auth import authenticate,login
# from .models import Candidate
from django.views.generic import View,ListView, DetailView
from django.contrib.auth.models import User
from .forms import LoginForm,CandidateForm
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.template import loader

from registration.models import Candidate,Student,Party,College,Post,Election

def login(request):

    election_list = Election.objects.all()
    if request.method == 'POST':
        selected_student_name = (request.POST['student_name'])
        selected_student_citizenship = (request.POST['student_citizenship'])
        global selected_election_id
        selected_election_id = request.POST['election']
        # print(selected_election_id)
        # selected_election_id = int(selected_election.election_id)
        party_list = Party.objects.all().order_by('party_id')
        candidate_list = Candidate.objects.all().filter(election_id = selected_election_id ).order_by('party_id')
        student_list = Student.objects.all().filter()

        for student in student_list:
            # print("Inside For Loop")
            # print ((student.name).replace(" ", ""))
            # print((selected_student_name.upper()).replace(" ", ""))
            if(student.name.upper().replace(" ", "") == selected_student_name.upper().replace(" ", "") and student.citizenship_no  == selected_student_citizenship) and student.has_voted == False:
                student.has_voted = True
                student.save()
                return render(request,'home/index.html', {'candidate_list': candidate_list,
                                                           'page_number': 0,
                                                           'party_list':party_list})
                # return HttpResponse((selected_student_name.upper(),selected_student_citizenship))
                # print("yes")
                # print(student.name.upper())
                # print(selected_student_name)
                # print(student.citizenship_no)
                # print(selected_student_citizenship)
                # break
            # return render(request,'home/log-in.html')
            # print("NO")

    return render(request,'home/log-in.html',{'election_list':election_list})
        # return login(request)




@login_required(login_url='/registration/')
def result(request):
    candidate_list = Candidate.objects.all().order_by('party_id')
    party_list =Party.objects.all()
    return render(request, 'home/result.html', {'candidate_list': candidate_list,
                                                'party_list':party_list,})

class IndexView(generic.ListView):

    template_name = 'home/index.html'
    model = Candidate
    context_object_name = 'candidate_list'

    def get_queryset(self):
        return Candidate.objects.order_by('name')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(IndexView, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        # context['page_number'] = 0
        context['party_list'] = Party.objects.all().order_by('party_id')
        return context


def voted(request):
    global selected_election_id
    party_list = Party.objects.all().order_by('party_id')
    candidate_list = Candidate.objects.all().filter(election_id =selected_election_id ).order_by('party_id')
    # candidate_list = Candidate.objects.order_by('name')#all()
    page_number = request.POST['page']

    try:
        selected_candidate = Candidate.objects.get(pk = request.POST['candidate'])

    except(KeyError,Candidate.DoesNotExist):
        page_number = int(page_number)
        # page_number = request.POST['page']
        # return render(request, home:voted, {'candidate_list': candidate_list,
        #                                            'page_number': page_number,})

        return render(request,'home/index.html', {'candidate_list': candidate_list,
                                                   'page_number': page_number,
                                                   'party_list':party_list,})
    else:
        selected_candidate.votes += 1
        selected_candidate.save()

        # page_number = request.POST['page']
        page_number += 1
        if page_number != 5:
            # page_number = ((int(page_number)+ 1))
            return render(request, 'home/index.html', {'candidate_list': candidate_list,
                                                       'page_number': page_number,
                                                       'party_list':party_list,})
        # return render(request, 'home/index.html', {'candidate_list': candidate_list,
        #                                            'page_number': page_number,})
        page_number = 0
        return redirect('home:log-in')

        # return render(request,'home/index.html', {'candidate_list': candidate_list,
        #                                           'page_number': page_number,})


def user_login(request):

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if not form.is_valid():
            return HttpResponse('Invalid Login')

        cd = form.cleaned_data
        user = authenticate(request,username = cd['username'],password = cd['password'])

        if user is not None:
            if not user.is_active:
                return HttpResponse('Account Disabled')

            login(request)
            candidates = Candidate.objects.order_by('name')
            return render(request, 'home/dashboard.html',{'candidates':candidates,
                                                         })
    else:
        form = LoginForm()

    return render(request, 'home/login.html', {'form': form})

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width = device-width, initial-scale = 1">
    <title>{% block title %}Home{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'home/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'home/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- <script type='text/javascript' src="{% static "home/bootstrap/js/jquery-3.2.1.js" %}"></script> -->
    {% block stylesheet %}
    {% endblock %}
</head>
<body>

{% block navbar %}
<div class="new">


<nav class="navbar navbar-default" style="background-image:url('media/electionSmall.png');">
  <div class="container-fluid">
    <div class="navbar-header">
      <!-- <a class="navbar-brand" href="#">WebSiteName</a> -->
    </div>
    <ul class="nav navbar-nav">
      <!-- <li class="active"><a href="#">Home</a></li> -->
      <li><a href="{% url 'registration:homeView' %}">Admin Panel</a></li>
      <!-- <li><a href="#">Page 2</a></li>
      <li><a href="#">Page 3</a></li> -->
    </ul>
  </div>
</nav>

</div>
{% endblock %}

{% block body %}
{% endblock %}
</body>
</html>


{% block js %}
{% endblock %}

home/templates/home/dashboard.html
{% extends 'home/base.html' %}

{% block title %} Admin Dashboard{% endblock %}

{% block body %}
  <h1>Log-in</h1>
    <p>This is the dashboard</p>

    {% for candidate in candidates  %}
      <li>
        <div class="candidate">

          <div class="col col-md-4">

              <!-- <a href="{% url 'home:candidate_detail' candidate.id %}">{{ candidate.name }}</a> -->

          </div>


          <div class="col col-md-4">
            <a href="{% url 'home:candidate_delete' candidate.id %}"><button class="btn btn-danger">Delete</button></a>
          </div>

          <div class="col col-md-4">
            <a href="{% url 'home:candidate_update' candidate.id %}"><button class="btn btn-danger">Update</button></a>
          </div>

        </div>
      </li>


    {% endfor %}

    <a href="{% url 'home:add_candidate' %}">Click here to add a new candidate</a>

{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}

{% load staticfiles %}

{% block stylesheet%}
<link rel="stylesheet" href="{% static 'home/Candidate.css' %}">
{% endblock %}

{% block title %} HomePage{% endblock %}

{% block navbar %}

{% endblock %}

{% block body %}
<div class="container">


<!-- {#{{ page_number }} = {% toint(page_number) %}#} -->
  {% if candidate_list %}
    {%if page_number == 0 %}
      <h3>Choose your Candidate's Party for the post of president</h3>
        <form action="{% url 'home:voted'  %}" method="POST">
          {% csrf_token %}

            {% for candidate in candidate_list %}

              {% if candidate.post.post_name == 'President'%}
                <div class="candidate-items">
                  <input type="radio" id = "candidate{{ forloop.counter }}" name = "candidate" value = "{{ candidate.candidate_id }}" />
                    <div class="candidate-card">


                      <label for="candidate{{ forloop.counter }}">
                        <!-- {{ candidate.party_id }}  -->
                        {% for party in party_list%}
                          {% if party.party_id == candidate.party_id %}

                            <img src="{{ party.symbol.url }}" alt="" class="img ">
                            <!-- <img src="{% static "home/media/swastikSymbol.png" alt="" class="img" %}"> -->
                            {{party.name}}
                            <div class="overlay">
                              <div class="text">
                                Click and press submit to vote
                              </div>
                            </div>
                          {% endif %}
                        {% endfor %}
                      </label>

                    </div>


                </div>
              {% endif %}

            {% endfor %}


            <input type="text" name="page" value="{{ page_number }}" />

            <div class="">
              <input type="submit" value="Submit" class = "btn btn-danger"  >
            </div>
        </form>
    {% endif %}
            <!-- {##} -->
    {%if page_number == 1 %}
      <h3>Choose your Candidate's Party for the post of Vice President</h3>
        <form action="{% url 'home:voted'  %}" method="POST">
            {% csrf_token %}

            {% for candidate in candidate_list %}
              {% if candidate.post.post_name == 'Vice President'%}
              <div class="candidate-items">
                <input type="radio" id = "candidate{{ forloop.counter }}" name = "candidate" value = "{{ candidate.candidate_id }}" />
                  <div class="candidate-card">


                    <label for="candidate{{ forloop.counter }}">
                      <!-- {{ candidate.party_id }}  -->
                      {% for party in party_list%}
                        {% if party.party_id == candidate.party_id %}

                          <img src="{{ party.symbol.url }}" alt="" class="img ">
                          <!-- <img src="{% static "home/media/swastikSymbol.png" alt="" class="img" %}"> -->
                          {{party.name}}
                          <div class="overlay">
                            <div class="text">
                              Click and press submit to vote
                            </div>
                          </div>
                        {% endif %}
                      {% endfor %}
                    </label>

                  </div>


              </div>
              {% endif %}

            {% endfor %}

            <input type="text" name="page" value="{{ page_number }}" />

            <div class="">
              <input type="submit" value="Submit" class = "btn btn-danger"  >
            </div>
        </form>
    {% endif %}

    {%if page_number == 2 %}
      <h3>Choose your Candidate's Party for the post of Secretary</h3>
        <form action="{% url 'home:voted'  %}" method="POST">
            {% csrf_token %}

            {% for candidate in candidate_list %}
              {% if candidate.post.post_name == 'Secretary'%}
              <div class="candidate-items">
                <input type="radio" id = "candidate{{ forloop.counter }}" name = "candidate" value = "{{ candidate.candidate_id }}" />
                  <div class="candidate-card">


                    <label for="candidate{{ forloop.counter }}">
                      <!-- {{ candidate.party_id }}  -->
                      {% for party in party_list%}
                        {% if party.party_id == candidate.party_id %}

                          <img src="{{ party.symbol.url }}" alt="" class="img ">
                          <!-- <img src="{% static "home/media/swastikSymbol.png" alt="" class="img" %}"> -->
                          {{party.name}}
                          <div class="overlay">
                            <div class="text">
                              Click and press submit to vote
                            </div>
                          </div>
                        {% endif %}
                      {% endfor %}
                    </label>

                  </div>


              </div>
              {% endif %}

            {% endfor %}

            <input type="text" name="page" value="{{ page_number }}" />

            <div class="">
              <input type="submit" value="Submit" class = "btn btn-danger"  >
            </div>
        </form>
    {% endif %}

    {%if page_number == 3 %}
      <h3>Choose your Candidate's Party for the post of Treasurer</h3>
        <form action="{% url 'home:voted'  %}" method="POST">
            {% csrf_token %}

            {% for candidate in candidate_list %}
              {% if candidate.post.post_name == 'Treasurer'%}
              <div class="candidate-items">
                <input type="radio" id = "candidate{{ forloop.counter }}" name = "candidate" value = "{{ candidate.candidate_id }}" />
                  <div class="candidate-card">


                    <label for="candidate{{ forloop.counter }}">
                      <!-- {{ candidate.party_id }}  -->
                      {% for party in party_list%}
                        {% if party.party_id == candidate.party_id %}

                          <img src="{{ party.symbol.url }}" alt="" class="img ">
                          <!-- <img src="{% static "home/media/swastikSymbol.png" alt="" class="img" %}"> -->
                          {{party.name}}
                          <div class="overlay">
                            <div class="text">
                              Click and press submit to vote
                            </div>
                          </div>
                        {% endif %}
                      {% endfor %}
                    </label>

                  </div>


              </div>
              {% endif %}

            {% endfor %}

            <input type="text" name="page" value="{{ page_number }}" />

            <div class="">
              <input type="submit" value="Submit" class = "btn btn-danger"  >
            </div>
        </form>
    {% endif %}

    {%if page_number == 4 %}
      <h3>Choose your Candidate's Party for the post of Member</h3>
        <form action="{% url 'home:voted'  %}" method="POST">
            {% csrf_token %}

            {% for candidate in candidate_list %}
              {% if candidate.post.post_name == 'Member'%}
              <div class="candidate-items">
                <input type="radio" id = "candidate{{ forloop.counter }}" name = "candidate" value = "{{ candidate.candidate_id }}" />
                  <div class="candidate-card">


                    <label for="candidate{{ forloop.counter }}">
                      <!-- {{ candidate.party_id }}  -->
                      {% for party in party_list%}
                        {% if party.party_id == candidate.party_id %}

                          <img src="{{ party.symbol.url }}" alt="" class="img ">
                          <!-- <img src="{% static "home/media/swastikSymbol.png" alt="" class="img" %}"> -->
                          {{party.name}}
                          <div class="overlay">
                            <div class="text">
                              Click and press submit to vote
                            </div>
                          </div>
                        {% endif %}
                      {% endfor %}
                    </label>

                  </div>


              </div>
              {% endif %}

            {% endfor %}

            <input type="text" name="page" value="{{ page_number }}" />

            <div class="">
              <input type="submit" value="Submit" class = "btn btn-danger"  >
            </div>
        </form>
    {% endif %}





  {%endif%}

</div>
{% endblock %}


<!-- {% block js %}
<script>


  $(document).ready(function() {
    $(".candidate-items input:radio").click(function() {

      // $("div.candidate-card >label > img:first-of-type").css("opacity",1);
      // $("div.candidate-card >label > img:nth-of-type(2)").css("opacity",0);
      // $("div.candidate-card >label > img:first-of-type").addClass("voting");
      $("div.candidate-card").addClass("voting");


     });

    $("input:radio").prop("checked", true).trigger("click");

  });
</script>
{% endblock %} -->

home/templates/home/log-in.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block stylesheet%}
<link rel="stylesheet" href="{% static 'home/log-in-style.css' %}">
{% endblock %}

{% block title %} HomePage{% endblock %}



{% block body %}

<div class="container">

  <div class="form">


    <form class="" action="{% url 'home:log-in'  %}" method="POST">
      {% csrf_token %}
      <p class = 'text-info'> Please fill the following form to cast your vote </p>
      <div class="row">
        <p class="col col-sm-6">Name</p>
        <input id = "student_name" type="text" name="student_name" value="" class="col col-sm-6" autofocus>
      </div>

      <div class="row">
        <p class="col col-sm-6">Citizenship Number</p>
        <input id = "citizenship_no" type="number" name="student_citizenship" value="Citizenship Number Here" class="col col-sm-6">
      </div>

      <div class="row">

        <p class="col col-sm-6">Election</p>
        <select class="col col-sm-6" name="election">
          {% for election in election_list %}
            <option value="{{election.election_id}}">{{election.name}}</option>
          {% endfor %}

        </select>
      </div>

    <div class="row">
      <p class="col col-sm-6"></p>
      <input id = 'submit-form' class = 'btn btn-info col col-sm-6 '  type="submit" value="SUBMIT">
    </div>



    </form>

  </div>

</div>
    <!-- <a href="{% url 'home:index' %}">Click Here To vote</a> -->
    <!-- <hr>
    <a href="{% url 'home:result' %}">Click Here To View Results</a> -->

</div>
{% endblock %}


{% block js %}

<script>
  $(document).ready(function(){

  });

</script>

{% endblock %}

home/templates/home/login.html
{% extends 'home/base.html' %}

{% block title %} Login Page{% endblock %}

{% block body %}
  <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Log-in"></p>
    </form>
{% endblock %}

home/templates/home/result.html
{% extends 'home/base.html' %}

{% block title %} HomePage{% endblock %}

{% load staticfiles %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'home/result.css' %}">
{% endblock %}

{% block navbar %}
<div class="new">


<nav class="navbar navbar-default" style="background-image:url('media/electionSmall.png');">
  <div class="container-fluid">
    <div class="navbar-header">
      <!-- <a class="navbar-brand" href="#">WebSiteName</a> -->
    </div>
    <ul class="nav navbar-nav">
      <!-- <li class="active"><a href="#">Home</a></li> -->
      <li><a href="{% url 'registration:homeView' %}">Admin Panel</a></li>
      <li><a href="{% url 'registration:winners' %}">Winner List</a></li>
      <!-- <li><a href="#">Page 2</a></li>
      <li><a href="#">Page 3</a></li> -->
    </ul>
  </div>
</nav>

</div>
{% endblock %}

{% block body %}

  <div class="row">
      <div class="col col-md-4" style="text:strong">
        <strong>Party</strong>
      </div>

      <div class="col col-md-4">
          <strong>Post</strong>
      </div>

      <div class="col col-md-4" style="text-align:left">
          <strong>Vote Obtained</strong>
      </div>

  </div>
<hr>
    {% for candidate in candidate_list %}
        <div class="row">
          <div class="col col-md-4">
            {% for party in party_list %}
              {% if candidate.party_id == party.party_id%}
                {{ party.name }}
              {% endif %}
            {% endfor %}
          </div>

          <div class="col col-md-4">
              {{ candidate.post }}
          </div>

          <div class="col col-md-4" style="text-align:left">
            {{ candidate.votes }}
          </div>


        </div>
    {% endfor %}

    <style media="screen">


      div.row{
        margin-left:10px;
        margin-top:10px;
        /*background-color: blue;*/
        margin-right: 10px;
      }
      div.row-top{
        margin-left:10px;
        margin-top:5px;
        margin-bottom: 10px;
        background-color: black;
      }

    </style>

{% endblock %}